#!/usr/bin/env python3
"""Build Localizable.xcstrings (zh-Hans → en) for Cutti iOS.

Run from anywhere:
    python3 ios/CuttiMobile/Scripts/build_xcstrings.py

Writes ios/CuttiMobile/Resources/Localizable.xcstrings. Re-run whenever you
add new user-visible Chinese strings — add the key + English translation
to TRANSLATIONS below, then rebuild the app.

Design: zh-Hans is the source language, so Chinese string literals in
SwiftUI Text/Label/Button/Alert/navigationTitle/... auto-resolve against
the catalog. English-source strings (brand/marketing copy) live in
EN_SOURCE with explicit zh-Hans translations.
"""
import json, os, sys

# All unique Chinese UI strings → English translations.
TRANSLATIONS = {
    "项目": "Projects",
    "%lld 个片段": "%lld clips",
    # Settings sheet
    "设置": "Settings",
    "完成": "Done",
    "账号": "Account",
    "订阅": "Subscription",
    "通用": "General",
    "视频剪辑": "Video Editor",
    "界面语言": "Interface Language",
    "开发者": "Developer",
    "关于": "About",
    "邮箱": "Email",
    "密码": "Password",
    "登录": "Sign In",
    "注册": "Sign Up",
    "登录方式": "Sign-in method",
    "登录 Cutti 账号": "Sign in to Cutti",
    "还没有账号？前往注册": "Don't have an account? Sign up",
    "退出登录": "Sign Out",
    "登录后即可使用云端 AI 功能（智能剪辑、视频摘要、章节建议等），订阅和额度在所有设备间同步。": "Sign in to unlock cloud AI features (Smart Cut, Summary, Chapters, etc.). Your subscription and credits sync across devices.",
    "计划": "Plan",
    "状态": "Status",
    "续期日": "Renews",
    "免费版": "Free",
    "本周期额度": "Credits this period",
    "默认显示字幕": "Show subtitles by default",
    "新建项目时字幕轨道默认可见。随时可以在时间线上手动切换。": "New projects start with the subtitle track visible. You can toggle it per-project on the timeline.",
    "识别语言": "Speech Language",
    "自动": "Automatic",
    "中文": "Chinese",
    "英语": "English",
    "选择视频中主要的说话语言。Cutti 会据此自动识别字幕。选「自动」时跟随系统语言。": "Choose the primary spoken language in your clips — used for automatic subtitle recognition. “Automatic” follows the system language.",
    "跟随系统": "System",
    "简体中文": "简体中文",
    "独立于上方识别语言。切换后需要重新打开 App 才能完全生效。": "Independent from the speech language above. Changing requires relaunching the app to fully apply.",
    "显示 AI 执行轨迹": "Show AI execution trace",
    "在 AI 执行过程中显示每一步的详细日志。日常使用无需打开。": "Reveals the step-by-step trace while AI runs. Off by default — you don't need this day-to-day.",
    "版本": "Version",
    "需要重启": "Restart Required",
    "切换界面语言需要重新打开 Cutti。新设置会在下次启动时生效。": "Changing the interface language requires relaunching Cutti. The new setting takes effect next launch.",
    "稍后手动重启": "I'll restart later",
    # Smart cut workflow phases / results — labels mirror macOS's
    # MediaCoreViewModel.updateAnalysisChatBubble user-facing phase
    # strings so zh/en readouts match the macOS app verbatim.
    "正在识别语音": "Transcribing speech",
    "正在分析音频": "Analyzing audio",
    "AI 正在规划剪辑": "Asking AI to plan cuts",
    "本地分析完成": "Local analysis complete",
    "语音识别失败：": "Speech recognition failed: ",
    "AI 剪辑失败：": "AI edit failed: ",
    "视频里没有可识别的语音,无法智能剪辑": "No recognizable speech in the video — smart cut can't run",
    "已智能裁掉 %lld 处,保留 %lld 句": "Cut %1$lld, kept %2$lld clips",
    # Trim-pauses preset (local-only, matches macOS smart.trimPauses)
    "仅去停顿": "Trim pauses only",
    "本地去掉沉默段,不动任何台词": "Drop silent gaps locally — every word is kept",
    "已裁掉 %lld 处停顿": "Trimmed %lld silent gaps",
    "没有检测到需要裁剪的停顿": "No silent gaps long enough to trim",
    # Transcript-cleanup preset (mirrors macOS smart.transcriptCleanup)
    "转写清理": "Transcript cleanup",
    "AI 删除重复、换词、半截句子": "AI deletes restarts, rewordings, half sentences",
    # Subtitle translation presets (mirrors macOS subtitle.* group)
    "字幕翻译": "Subtitles",
    "中英双语字幕": "Bilingual (中 ↔ EN)",
    "自动在中文和英文之间互译并双语显示": "Translate between Chinese and English, show both lines",
    "添加英文译文": "Add English translation line",
    "翻译每条字幕为英文并开启双语显示": "Translate every cue to English, show bilingual",
    "添加中文译文": "Add Chinese translation line",
    "翻译每条字幕为中文并开启双语显示": "Translate every cue to Chinese, show bilingual",
    "翻译到其他语言…": "Translate subtitles to…",
    "填写目标语言代码,AI 翻译并双语显示": "Pick the target language, AI translates and shows bilingual",
    "翻译目标语言": "Target language",
    "填写 BCP-47 语言代码,例如 ja / fr / es / zh-Hant": "Enter a BCP-47 code, e.g. ja / fr / es / zh-Hant",
    "翻译": "Translate",
    "取消": "Cancel",
    "翻译字幕": "Translate subtitles",
    "没有字幕可翻译": "No subtitles to translate",
    "正在翻译…": "Translating…",
    "已翻译 %lld 条字幕": "Translated %lld subtitle lines",
    "正在准备…": "Preparing…",
    # SubtitleTranslator errors
    "请先登录账号": "Please sign in first",
    "AI 返回为空": "AI returned an empty reply",
    "解析翻译结果失败：": "Failed to parse translation: ",
    "AI 回复不是预期的 JSON 格式": "AI reply was not the expected JSON shape",
    # Home dashboard (commercial-style landing page)
    "AI · 智能剪辑": "AI · Smart editing",
    "让 AI 帮你剪出好视频": "Let AI edit your videos",
    "一键裁掉停顿重复,自动生成字幕和章节": "One tap to cut silence & repeats, auto subtitles & chapters",
    "AI 自动裁掉停顿、重复、半句": "AI trims silence, repeats, half sentences",
    "开始新项目": "Start New Project",
    "热门 AI 玩法": "Featured AI",
    "全部": "See all",
    "我的项目": "My Projects",
    "还没有项目": "No projects yet",
    "点击上方开始新项目,或挑一个 AI 玩法试试": "Tap above to start a project, or try a featured AI tool",
    "智能字幕": "Auto subtitles",
    "本机 SFSpeech · 秒级识别": "On-device SFSpeech · fast",
    "去除口癖": "Remove fillers",
    "uh / um / 嗯 / 那个 一键净化": "Strip uh / um / like / etc.",
    "双语字幕": "Bilingual subs",
    "中英互译 · 云端 AI": "中 ↔ EN · cloud AI",
    "文字配音": "Text to speech",
    "Apple TTS · 多语种旁白": "Apple TTS · narration",
    "AI 图像": "AI image",
    "输入描述 · 生成贴图 / 封面": "Describe it · generate stickers / covers",
    # Runtime format-string keys used via L(key, args...)
    "垂直位置 %lld%%": "Vertical %lld%%",
    "已选 %@": "Selected %@",
    "译文 (%@)": "Translation (%@)",
    "语速 (%@)": "Rate (%@)",
    "音调 (%@)": "Pitch (%@)",
    " · 剩余 ~%.0fs": " · ~%.0fs left",
    "#话题": "#topic",
    "+ 添加音频": "+ Add Audio",
    "AI 工具箱": "AI Toolbox",
    "AI 根据内容划分章节并生成进度条": "AI splits the video into chapters and builds a progress bar",
    "AI 觉得每一句都值得保留,没有删改": "AI thinks every line is worth keeping — nothing was cut",
    "Aa 汉": "Aa 文",
    "Apple TTS 本机合成旁白": "On-device Apple TTS narration",
    "B-Roll 建议": "B-Roll Suggestions",
    "SFSpeech 本机识别 · 零依赖": "On-device SFSpeech · zero dependencies",
    "一段话概括视频内容": "Summarize the video in one paragraph",
    "一键删除 uh / um / 嗯 / 那个": "Strip uh / um / like / you know in one tap",
    "一键转场": "Apply Transitions",
    "一键静音某人的全部台词": "Mute every line from one speaker",
    "一键首剪": "Smart Cut",
    "下三分之一": "Lower Third",
    "不透明度": "Opacity",
    "中": "M",
    "中文 (简)": "Chinese (Simplified)",
    "中文 (繁)": "Chinese (Traditional)",
    "云端": "Cloud",
    "云端没有返回结果，请稍后再试。": "The cloud returned no result. Please try again later.",
    "亮度": "Brightness",
    "人声增强": "Voice Enhance",
    "优雅斜体": "Elegant Italic",
    "位置 X": "Position X",
    "位置 Y": "Position Y",
    "保存": "Save",
    "共 N 段，合计约 X 秒。": "N segments · about X seconds total.",
    "关闭原声": "Mute Source",
    "关闭双语": "Hide Bilingual",
    "其实": "actually",
    "写入相册失败": "Failed to save to Photos",
    "冷调": "Cool",
    "分享到其他应用": "Share to Other Apps",
    "分割": "Split",
    "分离音频": "Detach Audio",
    "分辨率": "Resolution",
    "列出某位讲话者的所有句子": "List every sentence from a given speaker",
    "删除": "Delete",
    "剪切": "Cut",
    "剪辑": "Edit",
    "加入转场": "Add Transition",
    "动效标题卡": "Animated Title Card",
    "原图": "Original",
    "去除口癖": "Remove Fillers",
    "双击编辑": "Double-tap to edit",
    "双语显示": "Show Bilingual",
    "发音人": "Voice",
    "取消": "Cancel",
    "取消导出": "Cancel Export",
    "取消转场": "Remove Transition",
    "取消静音": "Unmute",
    "变速": "Speed",
    "右移": "Move Right",
    "合并": "Merge",
    "合并回视频": "Merge Back into Video",
    "合并音频": "Merge Audio",
    "合成": "Compose",
    "合成中…": "Composing…",
    "合成失败": "Compose Failed",
    "呃": "uh",
    "啊": "ah",
    "嗯": "um",
    "嘉宾姓名": "Guest name",
    "图形": "Shapes",
    "在下方时间线点击片段来查看或编辑属性": "Tap a clip in the timeline below to view or edit its properties",
    "在强调段落插入 ChapterTitle 动画卡": "Insert an animated Chapter Title card on emphasized passages",
    "在播放头分割": "Split at Playhead",
    "在播放头新增章节": "Add Chapter at Playhead",
    "在线": "Online",
    "垂直 ✓": "Vertical ✓",
    "垂直翻转": "Flip Vertical",
    "垂直镜像": "Mirror Vertical",
    "声音": "Audio",
    "复制": "Copy",
    "复制副本": "Duplicate",
    "复古": "Retro",
    "大标题": "Headline",
    "好可爱": "So Cute",
    "字体": "Font",
    "字号": "Size",
    "字幕文本": "Subtitle Text",
    "字幕条数": "Subtitle Count",
    "字幕样式": "Subtitle Style",
    "字幕编辑": "Edit Subtitles",
    "完成": "Done",
    "对比度": "Contrast",
    "导入失败": "Import Failed",
    "导入字幕": "Import Subtitles",
    "导出": "Export",
    "导出 SRT": "Export SRT",
    "导出 VTT": "Export VTT",
    "导出失败": "Export Failed",
    "导出完成": "Export Complete",
    "导出视频": "Export Video",
    "封面": "Cover",
    "就是": "like",
    "属性": "Properties",
    "左移": "Move Left",
    "已保存到相册": "Saved to Photos",
    "已保存到相册,导入视频时可选": "Saved to Photos — available next time you import",
    "已取消": "Cancelled",
    "已复制": "Copied",
    "已应用片头片尾淡入淡出": "Head/tail fade applied",
    "已用 %.0fs": "Elapsed %.0fs",
    "已用 12s · 剩余 ~8s": "Elapsed 12s · ~8s left",
    "庆祝": "Celebrate",
    "应用到全部": "Apply to All",
    "开启原声": "Unmute Source",
    "开始导出": "Start Export",
    "开始录制": "Start Recording",
    "录音": "Record",
    "快": "Fast",
    "慢": "Slow",
    "手势": "Gestures",
    "打开背景": "Show Background",
    "拷贝": "Copy",
    "按语义切分每位讲话者": "Split by semantics per speaker",
    "按语义推荐空镜插入点": "Suggest B-roll insert points by semantics",
    "按转写生成 3 条候选标题": "Generate 3 title candidates from the transcript",
    "按转写自动裁掉沉默、重复、半句": "Auto-trim silences, repeats and half-sentences from the transcript",
    "接近黑画面或镜头被遮": "Near-black frames or covered lens",
    "描边": "Stroke",
    "描述一张图片 · 生成后保存到相册": "Describe an image · save to Photos after generating",
    "描述你想要的画面": "Describe the image you want",
    "提取某人台词": "Extract Speaker Lines",
    "提取音乐": "Extract Music",
    "提示": "Hint",
    "播放": "Play",
    "文件为空": "File is empty",
    "文字模板": "Text Templates",
    "文本": "Text",
    "文本样式": "Text Style",
    "文本转语音": "Text to Speech",
    "斜体": "Italic",
    "新建文本": "New Text",
    "旋转": "Rotate",
    "无": "None",
    "无法创建导出会话。": "Unable to create export session.",
    "无法读取视频": "Unable to read video",
    "无转场": "No Transition",
    "日本語": "Japanese",
    "时长": "Duration",
    "时间线上没有可加转场的切点": "No cut points on the timeline to add a transition",
    "时间线为空": "Timeline is empty",
    "时间线太短，无法生成章节。": "Timeline is too short to generate chapters.",
    "智能剪辑": "Smart Edit",
    "智能字幕": "Smart Subtitles",
    "智能片头 / 智能片尾": "Smart Intro / Outro",
    "暖阳": "Warm Sun",
    "暗角": "Vignette",
    "替换": "Replace",
    "替换为": "Replace with",
    "未匹配到任何片段": "No matching segments",
    "未找到 JSON 数组": "No JSON array found",
    "未授权写入相册": "Not authorized to save to Photos",
    "未检测到口癖词": "No filler words detected",
    "未知错误": "Unknown error",
    "未能解析出任何章节": "Could not parse any chapters",
    "未选中片段": "No clip selected",
    "本机专属": "On-device Only",
    "柔光": "Soft Light",
    "查找": "Find",
    "查找替换": "Find & Replace",
    "查找空镜": "Find B-Roll Spans",
    "查找黑场": "Find Black Frames",
    "标签": "Tag",
    "标题": "Title",
    "标题建议": "Title Suggestions",
    "模糊": "Blur",
    "正在保存到相册…": "Saving to Photos…",
    "正在准备…": "Preparing…",
    "正在增强人声…": "Enhancing voice…",
    "正在渲染…": "Rendering…",
    "正在生成…": "Generating…",
    "正在识别…": "Transcribing…",
    "正在识别全部片段…": "Transcribing all clips…",
    "正在识别语音…": "Transcribing speech…",
    "比例": "Ratio",
    "水平 ✓": "Horizontal ✓",
    "水平翻转": "Flip Horizontal",
    "水平镜像": "Mirror Horizontal",
    "没有匹配项": "No matches",
    "没有可导出的片段。": "No clips to export.",
    "没有可建议的画中画 — 添加 PiP 后再试": "Nothing to suggest — add a PiP first, then retry",
    "没有可识别的片段": "No clips to transcribe",
    "没有识别到任何字幕条目": "No subtitle entries detected",
    "没有音频可写出": "No audio to write",
    "浅粉": "Light Pink",
    "浅绿": "Light Green",
    "浅蓝": "Light Blue",
    "淡入": "Fade In",
    "淡入淡出": "Fade In/Out",
    "淡出": "Fade Out",
    "深蓝": "Deep Blue",
    "添加": "Add",
    "添加文本": "Add Text",
    "添加画中画": "Add PiP",
    "添加译文": "Add Translation",
    "添加贴纸": "Add Sticker",
    "添加音乐": "Add Music",
    "添加音频": "Add Audio",
    "清新一夏": "Fresh Summer",
    "清除全部": "Clear All",
    "滤镜": "Filter",
    "漫画": "Comic",
    "灰": "Gray",
    "炸裂！": "Epic!",
    "点击右上角 「识别全部」 开始转写。": "Tap \"Transcribe All\" in the top right to start.",
    "热成像": "Thermal",
    "热血红": "Hot Red",
    "热门": "Popular",
    "然后": "then",
    "片头片尾淡入淡出": "Head/Tail Fade",
    "特效": "Effects",
    "状态异常": "Unexpected State",
    "王老师": "Teacher Wang",
    "珊瑚": "Coral",
    "甜心粉": "Sweet Pink",
    "生成": "Generate",
    "生成 AI 图像": "Generate AI Image",
    "生成中…": "Generating…",
    "生成创作": "Generate",
    "用视频画面填充背景": "Fill background with the video frame",
    "电光青": "Electric Cyan",
    "画中画": "Picture-in-Picture",
    "画面": "Canvas",
    "画面分析": "Frame Analysis",
    "画面比例": "Aspect Ratio",
    "画面里全程都有人出现，没有检测到空镜。": "Faces are present throughout — no empty B-roll spans detected.",
    "画面里没有人脸的区间": "Spans without any face in frame",
    "白": "White",
    "白色": "White",
    "神秘力": "Mystic",
    "空镜（无人脸）": "B-Roll (No Face)",
    "章节": "Chapters",
    "章节标题": "Chapter Title",
    "章节自动切分": "Auto-chapter",
    "等宽代码": "Monospace",
    "米色": "Beige",
    "粘贴": "Paste",
    "系统": "System",
    "系统不支持当前语言的语音识别。": "Speech recognition is not available for the current language.",
    "系统默认": "System Default",
    "经典字幕": "Classic Subtitle",
    "给所有切点加入平滑转场": "Add a smooth transition at every cut",
    "编码失败": "Encoding failed",
    "编辑文字": "Edit Text",
    "缩放": "Scale",
    "背景": "Background",
    "背景透明度": "Background Opacity",
    "背景音乐": "Background Music",
    "胶片": "Film",
    "自动为首尾加入缓入缓出": "Auto ease-in/ease-out for intro and outro",
    "自动画中画": "Auto PiP",
    "自然": "Natural",
    "自由变换": "Free Transform",
    "自由文字": "Free Text",
    "色彩调节": "Color Adjust",
    "花字": "Fancy Text",
    "范围": "Range",
    "蒙版": "Mask",
    "薄荷绿": "Mint",
    "表情": "Emoji",
    "视频亮度正常，没有检测到黑场。": "Video brightness looks normal — no black frames detected.",
    "视频已保存到相册": "Video saved to Photos",
    "视频摘要": "Video Summary",
    "设置封面": "Set Cover",
    "识别 presenter-cam 并按推荐布局放置": "Detect presenter-cam and place by recommended layout",
    "识别全部": "Transcribe All",
    "识别说话人": "Detect Speakers",
    "语音识别暂时不可用。": "Speech recognition is temporarily unavailable.",
    "说话人": "Speaker",
    "请允许访问照片才能保存导出。": "Please grant Photos access to save the export.",
    "请允许语音识别权限。": "Please grant Speech Recognition permission.",
    "请先在时间轴选中一个片段": "Please select a clip in the timeline first",
    "请先在时间轴选中一个画中画片段": "Please select a picture-in-picture clip first",
    "请先添加一段画中画或叠加素材": "Please add a picture-in-picture or overlay clip first",
    "请先添加视频": "Please add a video first",
    "请先添加视频片段": "Please add a video clip first",
    "找不到视频文件": "Video file not found",
    "请先登录 Cutti 账号以调用云端 AI。": "Please sign in to your Cutti account to use cloud AI.",
    "请先运行 智能字幕": "Please run Smart Subtitles first",
    "请先运行「智能字幕」，让我知道视频讲了什么。": "Please run Smart Subtitles first so I know what the video says.",
    "请前往 AI 工具箱 → 智能字幕": "Head to AI Toolbox → Smart Subtitles",
    "请输入字幕": "Enter subtitle text",
    "调节": "Adjust",
    "贴纸": "Stickers",
    "贴纸库": "Sticker Library",
    "转场": "Transition",
    "转场时长": "Transition Duration",
    "输入文字…": "Enter text…",
    "输入文本…": "Enter text…",
    "返回": "Back",
    "还没有字幕": "No subtitles yet",
    "还没有字幕，无法导出": "No subtitles yet — nothing to export",
    "还没有章节。点击底部按钮在播放头新增。": "No chapters yet. Tap the button below to add one at the playhead.",
    "这个": "like",
    "这个文件没有可分析的视频轨": "This file has no analyzable video track",
    "迷幻紫": "Psychedelic Purple",
    "选择片段": "Pick Clip",
    "透明度": "Opacity",
    "速度": "Speed",
    "那个": "you know",
    "重命名章节": "Rename Chapter",
    "重磅": "Big Reveal",
    "重置": "Reset",
    "重置为默认": "Reset to Default",
    "隐藏": "Hide",
    "隐藏查找": "Hide Find",
    "需要云端 LLM · 即将开放": "Needs cloud LLM · coming soon",
    "需要麦克风权限才能录音": "Microphone permission is required to record",
    "霓虹黄": "Neon Yellow",
    "静音": "Mute",
    "静音某位说话人": "Mute a Speaker",
    "音量": "Volume",
    "音频": "Audio",
    "预设": "Presets",
    "颜色": "Color",
    "食物": "Food",
    "饱和度": "Saturation",
    "马赛克": "Mosaic",
    "高通 + 动态 + 限幅 · 本机离线": "High-pass + dynamics + limiter · on-device",
    "鲜艳": "Vivid",
    "黄": "Yellow",
    "黑": "Black",
    "黑场 / 遮挡": "Black / Covered",
    "黑白": "Mono",
    "黑色": "Black",
}

# Verify all source strings are covered.
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(REPO, 'Sources')
OUT = os.path.join(REPO, 'Resources', 'Localizable.xcstrings')

import re
_cn = re.compile(r'"([^"\\]*[\u4e00-\u9fff]+[^"\\]*)"')
source = set()
for root, _, files in os.walk(SRC_DIR):
    for f in files:
        if not f.endswith('.swift'):
            continue
        for line in open(os.path.join(root, f)):
            if line.lstrip().startswith(('//', '///', '*')):
                continue
            for m in _cn.finditer(line):
                source.add(m.group(1))

missing = source - set(TRANSLATIONS.keys())
extra = set(TRANSLATIONS.keys()) - source
# Don't fail on extras — we add runtime interpolation keys + navigation titles
# that don't appear as bare literals in the grep.
if missing:
    print(f'MISSING: {missing}', file=sys.stderr)
    sys.exit(1)

catalog = {
    "sourceLanguage": "zh-Hans",
    "strings": {
        key: {
            "extractionState": "manual",
            "localizations": {
                "en": {
                    "stringUnit": {
                        "state": "translated",
                        "value": val,
                    }
                },
                "zh-Hans": {
                    "stringUnit": {
                        "state": "translated",
                        "value": key,
                    }
                },
            },
        }
        for key, val in TRANSLATIONS.items()
    },
    "version": "1.0",
}

# Strings whose source is English (e.g. "New Project" literals in code):
# need explicit zh-Hans translations instead of echoing the key.
EN_SOURCE = {
    "Cutti": ("Cutti", "Cutti"),
    "AI-powered video editing": ("AI-powered video editing", "AI 驱动的视频编辑"),
    "New Project": ("New Project", "新建项目"),
}
for key, (en_val, zh_val) in EN_SOURCE.items():
    catalog["strings"][key] = {
        "extractionState": "manual",
        "localizations": {
            "en": {"stringUnit": {"state": "translated", "value": en_val}},
            "zh-Hans": {"stringUnit": {"state": "translated", "value": zh_val}},
        },
    }

out = OUT
with open(out, 'w') as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2, sort_keys=True)
print(f'Wrote {len(catalog["strings"])} strings to {out}')
