// Auto-extracted from TimelineDock.swift — see commit log for rationale.
// Contents are moved verbatim; no behaviour changes.

import SwiftUI
import CuttiKit

/// Creative-action callbacks + read-only state surfaced by the timeline
/// UI for Phase 3 manual entry points (crossfade, insert B-roll, visual
/// markers, overlay lane). Bundled into an environment value so we don't
/// have to expand `TimelineDock`'s already-overlarge initializer (the
/// Swift type-checker refuses larger signatures).
struct TimelineCreativeActions {
    struct BRollOption: Identifiable, Equatable {
        let id: UUID
        let name: String
    }
    struct OverlaySegmentHint: Identifiable, Equatable {
        let id: UUID
        let startSeconds: Double
        let durationSeconds: Double
        let mediaName: String
        /// Backing clip ID — used to resolve a proxy URL for the
        /// filmstrip thumbnail so overlay pills render with the same
        /// visuals as primary-track pills rather than just a label.
        let sourceVideoID: UUID
        /// Source-time range the overlay pulls from, used by the
        /// filmstrip to pick representative frames.
        let sourceStartSeconds: Double
        let sourceEndSeconds: Double
        /// Per-segment visibility + mute, mirrored into the hint so the
        /// overlay pill can render the eye/speaker icons and their
        /// active/inactive state without reaching back into the view
        /// model.
        var isVideoHidden: Bool = false
        var isAudioMuted: Bool = false
        /// Current PiP layout so the context menu can show the active
        /// corner/shape as checked. Nil = legacy full-cover overlay.
        var pipLayout: PiPLayout? = nil
        /// True when this overlay was generated by the AI / Remotion
        /// pipeline (i.e. its backing segment carries an `overlaySpec`).
        /// Used to gate the "double-click opens the Inspector" gesture
        /// and the ✨ affordance on the pill.
        var isAIEditable: Bool = false
        /// True while the overlay's Remotion render (initial or
        /// Inspector-triggered re-render) is still in flight. Drives a
        /// dimmed + spinner state on the pill so the user knows the
        /// movie they're seeing is stale.
        var isRendering: Bool = false
    }
    struct OverlayRow: Identifiable, Equatable {
        let id: UUID
        let name: String
        let segments: [OverlaySegmentHint]
        /// Track-level state driving the gutter icons. `isMuted`
        /// mirrors the backing `Track.isMuted`; `isLocked` mirrors
        /// the new `Track.isLocked` flag (see Project.swift).
        var isMuted: Bool = false
        var isLocked: Bool = false
    }
    struct MarkerHint: Identifiable, Equatable {
        let id = UUID()
        let composedStart: Double
        let composedEnd: Double
        let kind: String
    }

    /// Projected B-roll suggestion ready to render as a bubble above V1.
    struct BRollSuggestionHint: Identifiable, Equatable {
        let id: UUID
        let composedSeconds: Double
        /// How long the speaker's anchor window is (source end − source
        /// start). Carries through from the suggestion's source range so
        /// the click-time instruction can tell the agent to size the
        /// overlay's `durationSeconds` to match the voiceover.
        let anchorDurationSeconds: Double
        let kind: BRollSuggestion.Kind
        let prompt: String
        let rationale: String
        /// Crisp ≤20-char card title in the transcript's language.
        /// Seeds the popover textfield. Optional for back-compat with
        /// suggestions persisted before this field existed.
        let userTitle: String?
        /// Per-kind extracted signal (e.g. `item1 | item2 | item3`)
        /// the downstream agent can lift directly into overlay props.
        /// Optional.
        let agentHint: String?
        /// Phase-1 section role (intro/thesis/enumeration/process/...).
        /// Drives deterministic template routing in
        /// `MediaCoreViewModel.buildOverlayInstruction`. Optional.
        let sectionRole: String?

        init(
            id: UUID,
            composedSeconds: Double,
            anchorDurationSeconds: Double,
            kind: BRollSuggestion.Kind,
            prompt: String,
            rationale: String,
            userTitle: String? = nil,
            agentHint: String? = nil,
            sectionRole: String? = nil
        ) {
            self.id = id
            self.composedSeconds = composedSeconds
            self.anchorDurationSeconds = anchorDurationSeconds
            self.kind = kind
            self.prompt = prompt
            self.rationale = rationale
            self.userTitle = userTitle
            self.agentHint = agentHint
            self.sectionRole = sectionRole
        }
    }

    /// One detached-audio clip mirrored onto an aux-audio track. Rendered
    /// as a pill on the A2 lane at `startSeconds` with `durationSeconds`
    /// width. `linkedV1ID` is set when the segment is still paired with
    /// a V1 clip (so the UI can offer "Reattach to Video" in its context
    /// menu); nil for orphaned aux audio.
    struct DetachedAudioSegmentHint: Identifiable, Equatable {
        let id: UUID
        let startSeconds: Double
        let durationSeconds: Double
        let mediaName: String
        let sourceVideoID: UUID
        let sourceStartSeconds: Double
        let sourceEndSeconds: Double
        let linkedV1ID: UUID?
    }
    struct DetachedAudioRow: Identifiable, Equatable {
        let id: UUID
        let name: String
        let segments: [DetachedAudioSegmentHint]
        var isMuted: Bool = false
        var isLocked: Bool = false
    }

    var onAddCrossfadeToNext: (Int, Double) -> Void = { _, _ in }
    var onAddCrossfadeFromPrevious: (Int, Double) -> Void = { _, _ in }
    var onInsertBRoll: (UUID, Double, Double) -> Void = { _, _, _ in }
    /// Called when the user drops a MediaBrowser record onto the primary
    /// video track. `index` is the primary-segment index to insert
    /// before (clamped to `[0, segments.count]`).
    var onInsertMediaAtPrimaryIndex: (UUID, Int) -> Void = { _, _ in }
    /// Called when the user drops a Highlights-panel row onto the
    /// primary video track. The slice `[sourceStart, sourceEnd]` is in
    /// source-video coordinates; `index` is the primary-segment index
    /// to insert before. Mirrors `onInsertMediaAtPrimaryIndex` but
    /// inserts a slice of the source instead of the full clip.
    var onInsertSourceSliceAtPrimaryIndex: (UUID, Double, Double, Int) -> Void = { _, _, _, _ in }
    /// Save a single V1 segment to the Highlights panel (the
    /// "Save to Highlights" context-menu entry-point). The view
    /// model maps composed segment → source range and writes a
    /// `.manual`-origin marker.
    var onSaveSegmentToHighlights: (UUID) -> Void = { _ in }
    /// Predicate gating the visibility/enabled-state of the
    /// "Save to Highlights" affordance. Returns false when the V1
    /// segment doesn't exist, its source has no AI snapshot, or the
    /// span would be too short to save. Wired so the menu item
    /// disables itself rather than failing post-click.
    var canSaveSegmentToHighlights: (UUID) -> Bool = { _ in false }
    /// Called when the user drops a MediaBrowser record onto an existing
    /// overlay (V2+) lane. `trackID` identifies the target overlay lane;
    /// `composedStart` is the drop x-coordinate translated into composed
    /// seconds. The view model appends a segment to that track instead
    /// of creating a new one (which the `onInsertBRoll` fallback does).
    var onInsertMediaIntoOverlayTrack: (UUID, UUID, Double) -> Void = { _, _, _ in }
    /// Called when the user repositions an overlay-track segment by
    /// dragging the pill or setting a numeric start time in the popover.
    /// `composedStart` is clamped ≥ 0 by the callee.
    var onMoveOverlaySegment: (UUID, Double) -> Void = { _, _ in }
    /// Called on trim-handle release (leading or trailing) of an
    /// overlay pill. `composedEdgeTime` is the absolute time on the
    /// composed timeline for the moving edge; the view model clamps
    /// to source duration and writes a single undo revision.
    var onTrimOverlaySegment: (UUID, HorizontalEdge, Double) -> Void = { _, _, _ in }
    /// Delete an overlay segment entirely. Removes the pill; if it was
    /// the only segment on its track, the track is removed too.
    var onRemoveOverlaySegment: (UUID) -> Void = { _ in }
    /// Toggle per-segment video visibility (eye icon on the pill).
    /// Works for both primary and overlay segments.
    var onToggleSegmentVideoHidden: (UUID) -> Void = { _ in }
    /// Toggle per-segment audio mute (speaker icon on the pill). Works
    /// for both primary and overlay segments.
    var onToggleSegmentAudioMuted: (UUID) -> Void = { _ in }
    /// Swap the primary take of `segmentID` with one of its
    /// alternate takes (identified by `alternativeTakeID`). The
    /// previous primary becomes an alternate on the same segment so
    /// the user can swap back.
    var onSwapAlternativeTake: (UUID, UUID) -> Void = { _, _ in }
    var onRefreshVisualMarkers: () -> Void = {}
    /// Dismiss a B-roll suggestion bubble. Persists as soft-delete on
    /// the owning record's snapshot.
    var onDismissBRollSuggestion: (UUID) -> Void = { _ in }
    /// Kick off a Remotion-rendered overlay derived from a B-roll
    /// suggestion. The view model picks the template + props and
    /// handles timeline placement; the strip just forwards the hint.
    var onGenerateBRollSuggestion: (TimelineCreativeActions.BRollSuggestionHint, String) -> Void = { _, _ in }
    /// Move V1's audio onto a shared detached-audio lane, muting V1.
    var onDetachAudio: (UUID) -> Void = { _ in }
    /// Inverse of Detach: unmute V1 and tear down the mirror aux clip.
    /// Accepts either the V1 segment's ID or the aux segment's ID.
    var onReattachAudio: (UUID) -> Void = { _ in }
    /// Delete a detached-audio segment initiated from the A2 lane. If
    /// the segment is still linked to a V1 clip, the view model will
    /// fall back to reattach so the V1 clip doesn't end up silent.
    var onDeleteDetachedAudio: (UUID) -> Void = { _ in }
    /// Apply or clear a Picture-in-Picture layout on an overlay segment.
    /// Pass `nil` to turn PiP off (overlay returns to full-cover).
    var onSetPiPLayout: (UUID, PiPLayout?) -> Void = { _, _ in }
    /// Run the Auto-PiP analyzer on an overlay segment: classify as
    /// presenter-cam + pick the best corner, then write the layout.
    var onAutoPiP: (UUID) -> Void = { _ in }
    /// Double-clicking an AI-generated overlay pill calls this with
    /// the segment id so the shell can open the floating Inspector
    /// panel. No-op for overlays that weren't AI-generated.
    var onOpenOverlayInspector: (UUID) -> Void = { _ in }
    /// Restore the source-time gap immediately BEFORE the segment at
    /// `index` — i.e. merge segment[index-1] and segment[index] back
    /// into one (or insert a new clip filling the gap when their
    /// effects differ). See `MediaCoreViewModel.restoreCutBetween`
    /// for behaviour. The view model decides the merge-vs-insert
    /// branch; the UI just dispatches the index.
    var onRestoreCutBefore: (Int) -> Void = { _ in }
    /// Symmetric to `onRestoreCutBefore`: restore the gap AFTER the
    /// segment at `index` (between segment[index] and segment[index+1]).
    var onRestoreCutAfter: (Int) -> Void = { _ in }
    /// Source-time gap (in seconds) that would be restored by
    /// `onRestoreCutBefore(index)`, or nil when no restorable cut is
    /// adjacent. The context menu uses the optional return to decide
    /// whether to surface the menu item, and the value to format the
    /// label ("Restore 2.4s cut before this clip").
    var restorableGapBefore: (Int) -> Double? = { _ in nil }
    /// Symmetric to `restorableGapBefore`.
    var restorableGapAfter: (Int) -> Double? = { _ in nil }
    var availableBRollMedia: [BRollOption] = []
    var overlayRows: [OverlayRow] = []
    var detachedAudioRows: [DetachedAudioRow] = []
    var markers: [MarkerHint] = []
    var bRollSuggestions: [BRollSuggestionHint] = []
    var isRefreshingMarkers: Bool = false
    var isEnabled: Bool = false
    /// Primary video track (V1) metadata surfaced for the gutter
    /// eye / lock buttons. `id` is nil only for an empty project
    /// that hasn't created a video track yet; in that case the
    /// buttons render non-interactive.
    var primaryVideoTrackID: UUID? = nil
    var primaryVideoMuted: Bool = false
    var primaryVideoLocked: Bool = false
    /// Global subtitles visibility. The S1 gutter eye couples to
    /// this flag since there is no dedicated subtitle Track in the
    /// model. Lock is intentionally absent for S1 (MVP).
    var subtitlesVisible: Bool = true
    /// Toggle a given Track's mute flag (`Track.isMuted`). For V1
    /// this silences primary audio via CompositionBuilder's new
    /// `primaryMuted` path; for overlay and aux audio tracks the
    /// pre-existing mute handling applies.
    var onToggleTrackMute: (UUID) -> Void = { _ in }
    /// Toggle a given Track's `isLocked` flag. All segment-targeted
    /// mutations on a locked track are no-ops.
    var onToggleTrackLocked: (UUID) -> Void = { _ in }
    /// Flip `MediaCoreViewModel.showSubtitles`. Called from the S1
    /// gutter eye button.
    var onToggleSubtitlesVisibility: () -> Void = {}
    nonisolated(unsafe) static let disabled = TimelineCreativeActions()
}

private struct TimelineCreativeActionsKey: EnvironmentKey {
    nonisolated(unsafe) static let defaultValue: TimelineCreativeActions = .disabled
}

extension EnvironmentValues {
    /// Creative-action callbacks + state for Phase 3 manual UI entry
    /// points (crossfade, insert B-roll, visual markers, overlay lane).
    var timelineCreativeActions: TimelineCreativeActions {
        get { self[TimelineCreativeActionsKey.self] }
        set { self[TimelineCreativeActionsKey.self] = newValue }
    }
}
